version: "3.6"
services:
  gregsithole-react-portfolio:
    build:
      context: $PWD/../..
      dockerfile: $PWD/Chirayuix-react-portfolio/Dockerfile
    restart: always
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=Chirayuix.com, www.Chirayuix.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=Chirayuix.com, www.Chirayuix.com
      - LETSENCRYPT_EMAIL=Chirayu1264@Gmail.com
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80
    depends_on:
      - Chirayuix-react-portfolio
    links:
      - Chirayuix-react-portfolio

networks:
  default:
    external:
      name: nginx-proxy